### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by proJM1** [Avdan-OS/AvdanOS#9]
I have a few questions with the AvdanOS listed below:

1. Is the AdvanOS just going to be the basic version or will it include the pro version?
2. Will the pro version be paid for or free?
3. Is it possible the run the AvdanOS as a .exe file?
4. Will it be possible to run files like exe, dmg and apk?
5. Will it be updated after its release?
6. How can I help, I would like to help with the AvdanOS but I'm not good with coding yet. Is it possible for me to be a beta tester, look for bugs or something along those lines? I have a lot of free time and I don't have much to do.
7. Is there any planned release date?
8. Will it stick 100% to the concept or will it have changes that are different to the concept?

**Comment by froxcey** [comment]
Yes, these questions are good questions. They have been asked multiple times but never actually written down like this. These answers are what I heard from discussion and are subject to changes.


> Is the AdvanOS just going to be the basic version or will it include the pro version?

Not sure, probably will come as a feature in basic version. Maybe make it so it can be enabled in avdanced settings? This is our best idea as of now.

> Will the pro version be paid for or free?

It will be completely free (freedom free) and open source. There will not be a part of the OS you need to unlock. The only restriction will be your PC hardware specs ;)

> Will it be possible to run AvdanOS as an .exe file?

It's impossible. You cannot run any operation system as executable. You can run virtual machine tho.

> Will it be possible to run files like exe, dmg and apk?

Yes, through well integrated compatibility layer or virtual machine 

> Will it be updated after its release?

Because this is based on Arch, it will most likely get rolling update. If we want it to survive, we will need to give it continuous security patches, bug fixes, new features, and updated APIs etc...

> How can I help, I would like to help with the AvdanOS but I'm not good with coding yet. Is it possible for me to be a beta tester, look for bugs or something along those lines? I have a lot of free time and I don't have much to do.

You can submit bug reports here or give inspiration on our [Discord server](discord.gg/avdanos). You can dream and make concepts (pencil and paper okay) and think outside the ~~box~~ monitor, and this might give us some important inspiration.

> Is there any planned release date?

ASAP

> Will it stick 100% to the concept or will it have changes that are different to the concept?

The concept video will be the default way to implement features, and it shouldn't change too much. However if there's something that's just not functional, we of course need to make an operation system that works. We also will need to add some of our own features.
